/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manoj
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        un = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        del = new javax.swing.JButton();
        Count = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        sh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        un.setText("                      ");

        jLabel2.setText("username");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        del.setText("Delete account");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        Count.setText("Count");
        Count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountActionPerformed(evt);
            }
        });

        ext.setText("Exit");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "USERID", "password", "phone", "email", "username", "ShowID", "seat", "toggle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl);

        jLabel5.setText("WELCOME TO THE ADMIN PAGE OF DAN CINEMAS");

        sh.setText("search");
        sh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shActionPerformed(evt);
            }
        });

        jButton1.setText("Delete seat record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("PRESS BUTTON TO EDIT MAINFRAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(sh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(del)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Count)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ext))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sh)
                    .addComponent(del)
                    .addComponent(ext)
                    .addComponent(jButton1)
                    .addComponent(Count))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        try{
            String p = JOptionPane.showInputDialog(this,"enter userID to be deleted");
            String q = "delete from signin where userID  ='"+p+"';";

            Statement stmt = con.createStatement();
           stmt.executeUpdate(q);
            refresh();

        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_delActionPerformed

    private void CountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountActionPerformed
        // TODO add your handling code here:
        try{
            String q = "select count(*) from signin natural join seats_booked;";
            Statement stmt = con.createStatement();
            int c = 0 ;
            ResultSet rs  = stmt.executeQuery(q);

            if(rs.next())
            c = rs.getInt(1);

            JOptionPane.showMessageDialog(this,"the no of customers are ="+c);
        } catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_CountActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_extActionPerformed

    private void shActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shActionPerformed
        // TODO add your handling code here:
         try{
            String p = JOptionPane.showInputDialog(this,"enter userID ");
            String q = "select * from signin natural join seats_booked  where userID  = '"+p+"';";

            Statement stmt = con.createStatement();
           ResultSet rs = stmt.executeQuery(q);
           DefaultTableModel dtm  = (DefaultTableModel)tbl.getModel();
         while(dtm.getRowCount()>0)
             dtm.removeRow(0);
         
         String ui2,p2,em2,un2,t; int ph,si,se ;
         
         while(rs.next()){
         
             ui2 = rs.getString(1);
     em2 = rs.getString(4);
     un2 = rs.getString(5);
     p2 = rs.getString(2);
     ph = rs.getInt(3);
     si = rs.getInt(6);
     se = rs.getInt(7);
     t = rs.getString(8);
     Object nr[] = {ui2,p2,ph,em2,un2,si,se,t};
         dtm.addRow(nr);
         
     }

        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

        
    }//GEN-LAST:event_shActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        opencon();
        refresh();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String p = JOptionPane.showInputDialog(this,"enter userID to be deleted");
            String q = "delete from seats_booked where userID  ='"+p+"';";

            Statement stmt = con.createStatement();
           stmt.executeUpdate(q);
            refresh();
         usr.u="Admin";
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
             
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       mainframe field= new mainframe();
                    field.setVisible(true);
                    setVisible(false);
                
    }//GEN-LAST:event_jButton2ActionPerformed
 Connection con ;
 void opencon(){
     try{
         Class.forName("java.sql.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost/IP_PROJECT","root","pass");
     } catch(Exception e ){
         JOptionPane.showMessageDialog(this,e.getMessage());
         
     }
 }
 void refresh(){
     try{
         String q = "select * from signin natural join seats_booked ;";
         Statement stmt = con.createStatement();
         
         ResultSet rs = stmt.executeQuery(q);
         DefaultTableModel dtm  = (DefaultTableModel)tbl.getModel();
         while(dtm.getRowCount()>0)
             dtm.removeRow(0);
         
         String ui2,p2,em2,un2,t; int ph,si,se ;
         
         while(rs.next()){
         
             ui2 = rs.getString(1);
     em2 = rs.getString(4);
     un2 = rs.getString(5);
     p2 = rs.getString(2);
     ph = rs.getInt(3);
     si = rs.getInt(6);
     se = rs.getInt(7);
     t = rs.getString(8);
     Object nr[] = {ui2,p2,ph,em2,un2,si,se,t};
         dtm.addRow(nr);
         
     }
    
     
     }catch(Exception e ){
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
 }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Count;
    private javax.swing.JButton del;
    private javax.swing.JButton ext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sh;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
