
import java.sql.Connection;
import java.sql.DriverManager;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static javafx.scene.paint.Color.color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manoj
 */
public class Thirdmovie extends javax.swing.JFrame {

    /**
     * Creates new form Thirdmovie
     */
    public Thirdmovie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        f2 = new javax.swing.JToggleButton();
        f5 = new javax.swing.JToggleButton();
        f3 = new javax.swing.JToggleButton();
        f6 = new javax.swing.JToggleButton();
        f = new javax.swing.JToggleButton();
        f4 = new javax.swing.JToggleButton();
        f7 = new javax.swing.JToggleButton();
        f8 = new javax.swing.JToggleButton();
        f9 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        da = new javax.swing.JComboBox<>();
        ui = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        f2.setBackground(new java.awt.Color(51, 255, 51));
        f2.setText("2");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        f5.setBackground(new java.awt.Color(51, 255, 51));
        f5.setText("5");
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });

        f3.setBackground(new java.awt.Color(51, 255, 51));
        f3.setText("3");
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        f6.setBackground(new java.awt.Color(51, 255, 51));
        f6.setText("6");
        f6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f6ActionPerformed(evt);
            }
        });

        f.setBackground(new java.awt.Color(102, 255, 51));
        f.setText("1");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        f4.setBackground(new java.awt.Color(51, 255, 51));
        f4.setText("4");
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        f7.setBackground(new java.awt.Color(51, 255, 51));
        f7.setText("7");
        f7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f7ActionPerformed(evt);
            }
        });

        f8.setBackground(new java.awt.Color(51, 255, 51));
        f8.setText("8");
        f8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f8ActionPerformed(evt);
            }
        });

        f9.setBackground(new java.awt.Color(51, 255, 51));
        f9.setText("9");
        f9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f9ActionPerformed(evt);
            }
        });

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        da.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018-07-01", "2018-07-02", "2018-07-03", "2018-07-04", "2018-07-05", "2018-07-06", "2018-07-07" }));
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });

        jButton1.setText("BOOKING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("PLEASE ENTER YOUR USER ID AND NAME TO CONTINUE");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\manoj\\Desktop\\IP\\DAN LOGO.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ui, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(f7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(f8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(f9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(f4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(f5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(f6))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(f)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(f2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(f3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(4, 4, 4)
                .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
        if(f2.isSelected()){

            f2.setBackground(Color.red);}

        if(!f2.isSelected()){

            f2.setBackground(Color.green);
        }
    }//GEN-LAST:event_f2ActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // TODO add your handling code here:
        if(f5.isSelected()){

            f5.setBackground(Color.red);}

        if(!f5.isSelected()){

            f5.setBackground(Color.green);
        }
    }//GEN-LAST:event_f5ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
        if(f3.isSelected()){

            f3.setBackground(Color.red);}

        if(!f3.isSelected()){

            f3.setBackground(Color.green);
        }
    }//GEN-LAST:event_f3ActionPerformed

    private void f6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f6ActionPerformed
        // TODO add your handling code here:
        if(f6.isSelected()){

            f6.setBackground(Color.red);}

        if(!f6.isSelected()){

            f6.setBackground(Color.green);
        }
    }//GEN-LAST:event_f6ActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
        if(f.isSelected()){
            f.setBackground(Color.red);}

        if(!f.isSelected()){

            f.setBackground(Color.green);
        }
    }//GEN-LAST:event_fActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:
        if(f4.isSelected()){

            f4.setBackground(Color.red);}

        if(!f4.isSelected()){

            f4.setBackground(Color.green);
        }
    }//GEN-LAST:event_f4ActionPerformed

    private void f7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f7ActionPerformed

    private void f8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f8ActionPerformed

    private void f9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        opencon();
        try{
            String sql = "select * from seats_booked ;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            String dn = (String)da.getSelectedItem();
 f.setEnabled(true);
  f2.setEnabled(true);
  f3.setEnabled(true);
  f4.setEnabled(true);
  f5.setEnabled(true);
  f6.setEnabled(true);
  f7.setEnabled(true);
  f8.setEnabled(true);
  f9.setEnabled(true);
  
            while(rs.next()){
                int  bk = rs.getInt("seat");
                String ds = rs.getString("date");
                int  g = rs.getInt("showID");
                if(g==3){
                if(ds.equalsIgnoreCase(dn)){

                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                     
                }

                if(ds.equalsIgnoreCase(dn)){

                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                   if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }

                if(ds.equalsIgnoreCase(dn)){

                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                    if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                 if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                     if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }

                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                    if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                    if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                }
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        opencon();
        try{
            String d1 = da.getSelectedItem().toString();
            int d2 = da.getSelectedIndex();
            String t = "05PM";
            double g  , r  ;
            String a = "";
            String s = ui.getText();
            if(f.isSelected()){
                g= 3 ;r= 1 ;a="f";
                String q = "insert into seats_booked values('"+s+"',"+g+"," + r+",'" +a+"','"+t+"','"+d1+"',"+d2+");" ;
                Statement st = con.createStatement();

                st.executeUpdate(q);

            }
            if(f2.isSelected()){
                g= 3 ;r= 2 ; a= "f2" ;
                String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
                Statement st = con.createStatement();

                st.executeUpdate(q);
            }
            if(f3.isSelected()){
                g= 3 ;r= 3 ; a = "f3";
                String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
                Statement st = con.createStatement();

                st.executeUpdate(q);
            }
            if(f4.isSelected()){
                g= 3 ;r= 4 ; a = "f4";
                String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
                Statement st = con.createStatement();

                st.executeUpdate(q);
            }
            if(f5.isSelected()){
                g= 3 ;r= 5 ; a = "f5";
                String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
                Statement st = con.createStatement();

                st.executeUpdate(q);
            }
            if(f6.isSelected()){
                g= 3 ;r= 6 ; a = "f6";
                String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
                Statement st = con.createStatement();

                st.executeUpdate(q);
            }
            if(f7.isSelected()){
              g= 1 ;r= 7 ; a = "f7";
         String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
     Statement st = con.createStatement();
     
      st.executeUpdate(q);
     }
         if(f8.isSelected()){
              g= 1 ;r= 8 ; a = "f8";
         String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
     Statement st = con.createStatement();
     
      st.executeUpdate(q);
     }
         if(f9.isSelected()){
              g= 1 ;r= 9 ; a = "f9";
         String q = "insert into seats_booked values('"+s+"',"+g+","+ r+",'"+a+"','"+t+"','"+d1+"',"+d2+");" ;
     Statement st = con.createStatement();
     
      st.executeUpdate(q);
         }

            JOptionPane.showMessageDialog(this,"Proceeding To Payment Page");
            Payment field= new Payment();
                    field.setVisible(true);
                    setVisible(false);
                     
        } catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainframe field= new mainframe();
                    field.setVisible(true);
                    setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        // TODO add your handling code here:
        
        opencon();
        try{
            String sql = "select * from seats_booked ;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            String dn = (String)da.getSelectedItem();
            int d = da.getSelectedIndex();
            while(rs.next()){
                int  bk = rs.getInt("seat");
                String ds = rs.getString("date");
                int  g = rs.getInt("showID");
                
                if(g==3){
                if(d==0){
                    if(ds.equalsIgnoreCase(dn)){

                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                    }
                }
                if(d==1){
                if(ds.equalsIgnoreCase(dn)){

                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                   if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                }
                if(ds.equalsIgnoreCase(dn)){

                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                    if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                 if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                     if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }

                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                    if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                if(ds.equalsIgnoreCase(dn)){
                    if (bk==1) {

                        f.setEnabled(false);
                    }
                    if (bk==2) {

                        f2.setEnabled(false);
                    }
                    if (bk==3) {

                        f3.setEnabled(false);
                    }
                    if (bk==4) {

                        f4.setEnabled(false);
                    }
                    if (bk==5) {

                        f5.setEnabled(false);
                    }
                    if (bk==6) {

                        f6.setEnabled(false);
                    }
                    if (bk==7) {
   
                f7.setEnabled(false);            
               }
           if (bk==8) {
   
                f8.setEnabled(false);            
               }
           if (bk==9) {
   
                f9.setEnabled(false);            
               }
                }
                }
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_daActionPerformed
 Connection con ;
 void opencon(){
     try{
         Class.forName("java.sql.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost/IP_PROJECT","root","pass");
     } catch(Exception e ){
         javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
         
     }
 }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thirdmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thirdmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thirdmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thirdmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thirdmovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> da;
    private javax.swing.JToggleButton f;
    private javax.swing.JToggleButton f2;
    private javax.swing.JToggleButton f3;
    private javax.swing.JToggleButton f4;
    private javax.swing.JToggleButton f5;
    private javax.swing.JToggleButton f6;
    private javax.swing.JToggleButton f7;
    private javax.swing.JToggleButton f8;
    private javax.swing.JToggleButton f9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ui;
    // End of variables declaration//GEN-END:variables
}
